#服务器端口和上下文
server:
  port: 8080
  servlet:
    context-path: /demo

#日志的配置
logging:
  file:
    path: e:/Project/log.log

#数据源的配置,以及配置热部署
#支持的最大文件和文件请求的最大值
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: jjddaybz520
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true

# mybatis映射文件的配置
mybatis:
  type-aliases-package: com.ddz.demo.po
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
