#服务器端口和上下文
server:
  port: 80
  servlet:
    context-path: /demo

#日志的配置
logging:
  file:
    path: e:/Project/log.log

#数据源的配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: jjddaybz520
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis映射文件的配置
mybatis:
  type-aliases-package: com.ddz.demo.po
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql